# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_index=True, max_length=100, verbose_name='内容')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='接收方是否已读')),
                ('is_hidden_from_sender', models.BooleanField(db_index=True, default=False, verbose_name='发送方是否隐藏（删除）该消息')),
                ('is_hidden_from_receiver', models.BooleanField(db_index=True, default=False, verbose_name='接收方是否隐藏（删除）该消息')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_send', related_query_name='message_send', to='project.Project', verbose_name='发送方项目')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', related_query_name='message_received', to='user.User', verbose_name='接收方')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_send', related_query_name='message_send', to='user.User', verbose_name='发送方')),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_send', related_query_name='message_send', to='team.Team', verbose_name='发送方团队')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-create_time'],
            },
        ),
    ]
