# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'location_city',
            },
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.City')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='project.Project')),
            ],
            options={
                'db_table': 'project_location',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('projects', models.ManyToManyField(related_name='_province_projects_+', through='location.ProjectLocation', to='project.Project')),
            ],
            options={
                'db_table': 'location_province',
            },
        ),
        migrations.CreateModel(
            name='TeamLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.City')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.Province')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='team.Team')),
            ],
            options={
                'db_table': 'team_location',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.City')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.Province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='user.User')),
            ],
            options={
                'db_table': 'user_location',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='teams',
            field=models.ManyToManyField(related_name='_province_teams_+', through='location.TeamLocation', to='team.Team'),
        ),
        migrations.AddField(
            model_name='province',
            name='users',
            field=models.ManyToManyField(related_name='_province_users_+', through='location.UserLocation', to='user.User'),
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location.Province'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', related_query_name='city', to='location.Province'),
        ),
    ]
