# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_index=True, default='', max_length=100, verbose_name='团队简介')),
                ('url', models.TextField(db_index=True, default='', max_length=100, verbose_name='相关链接')),
                ('is_recruiting', models.BooleanField(db_index=True, default=True, verbose_name='是否招募新成员')),
                ('icon', models.ImageField(upload_to='', verbose_name='团队图标')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='team.Team')),
            ],
            options={
                'db_table': 'team_profile',
            },
        ),
        migrations.CreateModel(
            name='UserEducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=20, verbose_name='学校')),
                ('degree', models.CharField(default='', max_length=2, verbose_name='学历')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('begin_time', models.DateField(blank=True, default=None, null=True, verbose_name='入学时间')),
                ('end_time', models.DateField(blank=True, default=None, null=True, verbose_name='毕业时间')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_experiences', related_query_name='education_experience', to='user.User')),
            ],
            options={
                'db_table': 'user_education_experience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserFieldworkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=20, verbose_name='公司')),
                ('position', models.CharField(default='', max_length=20, verbose_name='职位')),
                ('begin_time', models.DateField(blank=True, default=None, null=True, verbose_name='入职时间')),
                ('end_time', models.DateField(blank=True, default=None, null=True, verbose_name='离职时间')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldwork_experiences', related_query_name='fieldwork_experience', to='user.User')),
            ],
            options={
                'db_table': 'user_fieldwork_experience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='是否已通过实名认证')),
                ('name', models.CharField(db_index=True, default='', max_length=10, verbose_name='真实姓名')),
                ('number', models.CharField(default='', max_length=18, verbose_name='身份证号')),
                ('photo', models.ImageField(upload_to='', verbose_name='身份证照片')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification', to='user.User')),
            ],
            options={
                'db_table': 'user_identification',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_index=True, default='', max_length=100, verbose_name='个人简介')),
                ('gender', models.IntegerField(choices=[('保密', 0), ('男', 1), ('女', 1)], default=0, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='出生日期')),
                ('icon', models.ImageField(upload_to='', verbose_name='用户头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.User')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserStudentIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=20, verbose_name='学校名称')),
                ('number', models.CharField(default='', max_length=20, verbose_name='学生证号')),
                ('photo', models.ImageField(upload_to='', verbose_name='学生证照片')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_identification', to='user.User')),
            ],
            options={
                'db_table': 'user_student_identification',
            },
        ),
        migrations.CreateModel(
            name='UserWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=20, verbose_name='公司')),
                ('position', models.CharField(default='', max_length=20, verbose_name='职位')),
                ('begin_time', models.DateField(blank=True, default=None, null=True, verbose_name='入职时间')),
                ('end_time', models.DateField(blank=True, default=None, null=True, verbose_name='离职时间')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', related_query_name='work_experience', to='user.User')),
            ],
            options={
                'db_table': 'user_work_experience',
                'ordering': ['order'],
            },
        ),
    ]
