# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudentidentification',
            name='school',
            field=models.CharField(default='', max_length=20, verbose_name='学校名称'),
        ),
    ]
