# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('profiles', '0002_userstudentidentification_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=20, verbose_name='公司')),
                ('position', models.CharField(default='', max_length=20, verbose_name='职位')),
                ('begin_time', models.DateField(blank=True, default=None, null=True, verbose_name='入职时间')),
                ('end_time', models.DateField(blank=True, default=None, null=True, verbose_name='离职时间')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', related_query_name='work_experience', to='user.User')),
            ],
            options={
                'db_table': 'user_work_experience',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='usereducationexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_experiences', related_query_name='education_experience', to='user.User'),
        ),
        migrations.AlterField(
            model_name='userfieldworkexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldwork_experiences', related_query_name='fieldwork_experience', to='user.User'),
        ),
    ]
