import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ChuangYi.settings")
import django
from django.db import models
django.setup()

import inspect
import types
import codecs

# user

import main.models.user as users

url_text = """# Auto generated by generate.py
from django.conf.urls import url

from admin.views.user import *

urls = ["""

view_text = """# Auto generated by generate.py
from django import forms
from django.http import HttpResponse
from django.template import loader, Context
from django.views.generic import View

from main.models.user import *

from admin.utils.decorators import *
"""
view_class_text = """class {{cls_name}}View(View):
    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("user/{{tbl_name}}.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        {{args}}
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("{{tbl_name}}", mod.id, 1, request.user)

        template = loader.get_template("user/{{tbl_name}}.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class {{cls_name}}List(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = {{cls_name}}.objects.filter(user_id=kwargs["id"])
            template = loader.get_template("user/{{tbl_name}}_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:user:{{tbl_name}}'})
            return HttpResponse(template.render(context))
        elif request.GET.get("username") is not None:
            username = request.GET.get("username")
            template = loader.get_template("user/index.html")
            if {{cls_name}} == User:
                redir = 'admin:user:user'
            else:
                redir = 'admin:user:{{tbl_name}}_list'
            context = Context({'username': username, 'list': User.objects.filter(username=username), 'redir': redir, 'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("user/index.html")
            context = Context({'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
"""

for mod_name, mod_class in inspect.getmembers(users):
    if mod_name in users.__all__:
        template_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<form role="form" action="{% url 'admin:user:{{tbl_name}}' mod.id %}" method="post">
<table>
    {{content}}
    <tr>
        <td>{{ msg }}</td>
        <td>
            <div class="buttons">
                <input type="submit" value="保存" />
                <input type="reset" value="取消" />
            </div>
        </td>
    </tr>
</table>
</form>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='user_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='user_admin' lb='user' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='user_admin' lb='user' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
<style>
    form {
        padding: 30px;
    }
    form img {
        width: 100px;
        height: 100px;
    }
    td {
        padding: 5px 8px;
        vertical-align: top;
    }

    input[type=text], input[type=email], input[type=date], textarea {
        border: 2px solid #C5DBAD;
    }

    input[type=radio] {
        margin-right: 5px;
    }

    input[type=radio] ~ input {
        margin-left: 15px;
    }

    .buttons {
        float: right;
    }

    input[type=submit], input[type=reset] {
        border: 0 none;
        border-radius: 3px;
        padding: 2px 5px;
        background: #85A365;
        color: white;
        margin-left: 10px;
        margin-top: 10px;
    }

    input.tiny {
        width: 60px;
    }
</style>
{% endblock %}
"""
        template_contet_text = """<tr><td>{{text}}：</td><td><input name="{{name}}" type="{{type}}" value="{{ mod.{{name}} }}" {{minlen}}{{maxlen}}/></td></tr>"""
        template_contet_text2 = """<tr><td>{{text}}：</td><td><textarea name="{{name}}" {{minlen}}{{maxlen}}>{{ mod.{{name}} }}></textarea></td></tr>"""

        tbl_name = mod_class._meta.db_table
        
        url_text += "url(r'^" + tbl_name + "/list/(?P<id>\w+)?$', " + mod_name  + "List.as_view(), name='" + tbl_name + "_list'),url(r'^" + tbl_name + "/(?P<id>\w+)$', " + mod_name  + "View.as_view(), name='" + tbl_name + "'),"

        args_text = ""
        content_text = ""
        for fld in mod_class._meta.get_fields():
            if isinstance(fld, models.CharField):
                if fld.name == 'password':
                    continue
                args_text += "'" + fld.name + "': forms.CharField(" + ("max_length=" + str(fld.max_length) + "," if (fld.max_length is not None and fld.max_length > 0) else "") + ("required=False," if (fld.null or fld.default == '') else "") + "),"
                if fld.name == 'gender':
                    content_text += '<tr><td>' + fld.name + '：</td><td>{% include "parts/gender.html" %}</td></tr>'
                elif fld.name == 'description':
                    content_text += '<tr><td>' + fld.name + '：</td><td><textarea name=' + fld.name + '>{{ mod.' + fld.name + ' }}</textarea></td></tr>'
                else:
                    content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'text').replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.BooleanField):
                args_text += "'" + fld.name + "': forms.BooleanField(required=False),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'checkbox').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateTimeField):
                args_text += "'" + fld.name + "': forms.DateTimeField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'datetime').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateField):
                args_text += "'" + fld.name + "': forms.DateField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'date').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.TextField):
                args_text += "'" + fld.name + "': forms.CharField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text2.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.IntegerField):
                args_text += "'" + fld.name + "': forms.IntegerField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.FloatField):
                args_text += "'" + fld.name + "': forms.FloatField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.ForeignKey):
                content_text += '<tr><td>' + fld.name + '：</td><td><a href="{% url "admin:user:' + fld.rel.to._meta.db_table + '" mod.' + fld.name + '.id %}">{{ mod.' + fld.name + '.id }}</a></td></tr>'
        
        view_text += view_class_text.replace('{{cls_name}}', mod_name).replace('{{tbl_name}}', tbl_name).replace('{{args}}', args_text)
        template_file = codecs.open("./admin/templates/user/" + tbl_name + ".html", "w", "utf-8")
        template_file.write(template_text.replace('{{content}}', content_text).replace('{{tbl_name}}', tbl_name))
        template_file.close()

        template2_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<table style="margin:30px">
    {% for item in list %}
        <tr>
            <td>用户名： </td>
            <td style="min-width: 200px;border:1px solid #C4D9AE;">{{ item.user.name }}</td>
            <td><a href="{% url 'admin:user:{{tbl_name}}' item.user.id %}">查看</a></td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='user_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='user_admin' lb='user' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='user_admin' lb='user' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
{% include 'parts/input_style.html' %}
{% endblock %}
"""
        template2_file = codecs.open("./admin/templates/user/" + tbl_name + "_list.html", "w", "utf-8")
        template2_file.write(template2_text.replace('{{tbl_name}}', tbl_name))
        template2_file.close()

url_text += "]"
url_file = codecs.open("./admin/urls/user.py", "w", "utf-8")
url_file.write(url_text)
url_file.close()

view_file = codecs.open("./admin/views/user.py", "w", "utf-8")
view_file.write(view_text)
view_file.close()




# team

import main.models.team as teams

url_text = """# Auto generated by generate.py
from django.conf.urls import url

from admin.views.team import *

urls = ["""

view_text = """# Auto generated by generate.py
from django import forms
from django.http import HttpResponse
from django.template import loader, Context
from django.views.generic import View

from main.models.team import *

from admin.utils.decorators import *
"""
view_class_text = """class {{cls_name}}View(View):
    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("team/{{tbl_name}}.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        {{args}}
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("{{tbl_name}}", mod.id, 1, request.user)

        template = loader.get_template("team/{{tbl_name}}.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class {{cls_name}}List(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = {{cls_name}}.objects.filter(team_id=kwargs["id"])
            template = loader.get_template("team/{{tbl_name}}_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:team:{{tbl_name}}'})
            return HttpResponse(template.render(context))
        elif request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("team/index.html")
            if {{cls_name}} == Team:
                redir = 'admin:team:team'
            else:
                redir = 'admin:team:{{tbl_name}}_list'
            context = Context({'name': name, 'list': Team.objects.filter(name=name), 'redir': redir, 'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("team/index.html")
            context = Context({'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
"""

for mod_name, mod_class in inspect.getmembers(teams):
    if mod_name in teams.__all__:
        template_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<form role="form" action="{% url 'admin:team:{{tbl_name}}' mod.id %}" method="post">
<table>
    {{content}}
    <tr>
        <td>{{ msg }}</td>
        <td>
            <div class="buttons">
                <input type="submit" value="保存" />
                <input type="reset" value="取消" />
            </div>
        </td>
    </tr>
</table>
</form>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='user_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='user_admin' lb='team' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='user_admin' lb='team' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
<style>
    form {
        padding: 30px;
    }
    form img {
        width: 100px;
        height: 100px;
    }
    td {
        padding: 5px 8px;
        vertical-align: top;
    }

    input[type=text], input[type=email], input[type=date], textarea {
        border: 2px solid #C5DBAD;
    }

    input[type=radio] {
        margin-right: 5px;
    }

    input[type=radio] ~ input {
        margin-left: 15px;
    }

    .buttons {
        float: right;
    }

    input[type=submit], input[type=reset] {
        border: 0 none;
        border-radius: 3px;
        padding: 2px 5px;
        background: #85A365;
        color: white;
        margin-left: 10px;
        margin-top: 10px;
    }

    input.tiny {
        width: 60px;
    }
</style>
{% endblock %}
"""
        template_contet_text = """<tr><td>{{text}}：</td><td><input name="{{name}}" type="{{type}}" value="{{ mod.{{name}} }}" {{minlen}}{{maxlen}}/></td></tr>"""
        template_contet_text2 = """<tr><td>{{text}}：</td><td><textarea name="{{name}}" {{minlen}}{{maxlen}}>{{ mod.{{name}} }}></textarea></td></tr>"""

        tbl_name = mod_class._meta.db_table
        
        url_text += "url(r'^" + tbl_name + "/list/(?P<id>\w+)?$', " + mod_name  + "List.as_view(), name='" + tbl_name + "_list'),url(r'^" + tbl_name + "/(?P<id>\w+)$', " + mod_name  + "View.as_view(), name='" + tbl_name + "'),"

        args_text = ""
        content_text = ""
        for fld in mod_class._meta.get_fields():
            if isinstance(fld, models.CharField):
                if fld.name == 'password':
                    continue
                args_text += "'" + fld.name + "': forms.CharField(" + ("max_length=" + str(fld.max_length) + "," if (fld.max_length is not None and fld.max_length > 0) else "") + ("required=False," if (fld.null or fld.default == '') else "") + "),"
                if fld.name == 'gender':
                    content_text += '<tr><td>' + fld.name + '：</td><td>{% include "parts/gender.html" %}</td></tr>'
                elif fld.name == 'description':
                    content_text += '<tr><td>' + fld.name + '：</td><td><textarea name=' + fld.name + '>{{ mod.' + fld.name + ' }}</textarea></td></tr>'
                else:
                    content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'text').replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.BooleanField):
                args_text += "'" + fld.name + "': forms.BooleanField(required=False),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'checkbox').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateTimeField):
                args_text += "'" + fld.name + "': forms.DateTimeField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'datetime').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateField):
                args_text += "'" + fld.name + "': forms.DateField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'date').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.TextField):
                args_text += "'" + fld.name + "': forms.CharField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text2.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.IntegerField):
                args_text += "'" + fld.name + "': forms.IntegerField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.FloatField):
                args_text += "'" + fld.name + "': forms.FloatField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.ForeignKey):
                content_text += '<tr><td>' + fld.name + '：</td><td><a href="{% url "admin:team:' + fld.rel.to._meta.db_table + '" mod.' + fld.name + '.id %}">{{ mod.' + fld.name + '.id }}</a></td></tr>'
        
        view_text += view_class_text.replace('{{cls_name}}', mod_name).replace('{{tbl_name}}', tbl_name).replace('{{args}}', args_text)
        template_file = codecs.open("./admin/templates/team/" + tbl_name + ".html", "w", "utf-8")
        template_file.write(template_text.replace('{{content}}', content_text).replace('{{tbl_name}}', tbl_name))
        template_file.close()

        template2_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<table style="margin:30px">
    <tr>
        {% for item in list %}
            <td>团队名： </td>
            <td style="min-width: 200px;border:1px solid #C4D9AE;">{{ item.team.name }}</td>
            <td><a href="{% url 'admin:team:{{tbl_name}}' item.team.id %}">查看</a></td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='user_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='user_admin' lb='team' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='user_admin' lb='team' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
{% include 'parts/input_style.html' %}
{% endblock %}
"""
        template2_file = codecs.open("./admin/templates/team/" + tbl_name + "_list.html", "w", "utf-8")
        template2_file.write(template2_text.replace('{{tbl_name}}', tbl_name))
        template2_file.close()

url_text += "]"
url_file = codecs.open("./admin/urls/team.py", "w", "utf-8")
url_file.write(url_text)
url_file.close()

view_file = codecs.open("./admin/views/team.py", "w", "utf-8")
view_file.write(view_text)
view_file.close()



# activity

import main.models.activity as activities

url_text = """# Auto generated by generate.py
from django.conf.urls import url

from admin.views.activity import *

urls = ["""

view_text = """# Auto generated by generate.py
from django import forms
from django.http import HttpResponse
from django.template import loader, Context
from django.views.generic import View

from main.models.activity import *

from admin.utils.decorators import *
"""
view_class_text = """class {{cls_name}}View(View):
    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("activity/{{tbl_name}}.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        {{args}}
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("{{tbl_name}}", mod.id, 1, request.user)

        template = loader.get_template("activity/{{tbl_name}}.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class {{cls_name}}List(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = {{cls_name}}.objects.filter(activity_id=kwargs["id"])
            template = loader.get_template("activity/{{tbl_name}}_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:activity:{{tbl_name}}'})
            return HttpResponse(template.render(context))
        elif request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("activity/index.html")
            if {{cls_name}} == Activity:
                redir = 'admin:activity:activity'
            else:
                redir = 'admin:activity:{{tbl_name}}_list'
            context = Context({'name': name, 'list': Activity.objects.filter(name=name), 'redir': redir, 'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("activity/index.html")
            context = Context({'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
"""

for mod_name, mod_class in inspect.getmembers(activities):
    if mod_name in activities.__all__:
        template_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<form role="form" action="{% url 'admin:activity:{{tbl_name}}' mod.id %}" method="post">
<table>
    {{content}}
    <tr>
        <td>{{ msg }}</td>
        <td>
            <div class="buttons">
                <input type="submit" value="保存" />
                <input type="reset" value="取消" />
            </div>
        </td>
    </tr>
</table>
</form>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='activity_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='activity_admin' lb='activity' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='activity_admin' lb='activity' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
<style>
    form {
        padding: 30px;
    }
    form img {
        width: 100px;
        height: 100px;
    }
    td {
        padding: 5px 8px;
        vertical-align: top;
    }

    input[type=text], input[type=email], input[type=date], textarea {
        border: 2px solid #C5DBAD;
    }

    input[type=radio] {
        margin-right: 5px;
    }

    input[type=radio] ~ input {
        margin-left: 15px;
    }

    .buttons {
        float: right;
    }

    input[type=submit], input[type=reset] {
        border: 0 none;
        border-radius: 3px;
        padding: 2px 5px;
        background: #85A365;
        color: white;
        margin-left: 10px;
        margin-top: 10px;
    }

    input.tiny {
        width: 60px;
    }
</style>
{% endblock %}
"""
        template_contet_text = """<tr><td>{{text}}：</td><td><input name="{{name}}" type="{{type}}" value="{{ mod.{{name}} }}" {{minlen}}{{maxlen}}/></td></tr>"""
        template_contet_text2 = """<tr><td>{{text}}：</td><td><textarea name="{{name}}" {{minlen}}{{maxlen}}>{{ mod.{{name}} }}></textarea></td></tr>"""

        tbl_name = mod_class._meta.db_table
        
        url_text += "url(r'^" + tbl_name + "/list/(?P<id>\w+)?$', " + mod_name  + "List.as_view(), name='" + tbl_name + "_list'),url(r'^" + tbl_name + "/(?P<id>\w+)$', " + mod_name  + "View.as_view(), name='" + tbl_name + "'),"

        args_text = ""
        content_text = ""
        for fld in mod_class._meta.get_fields():
            if isinstance(fld, models.CharField):
                if fld.name == 'password':
                    continue
                args_text += "'" + fld.name + "': forms.CharField(" + ("max_length=" + str(fld.max_length) + "," if (fld.max_length is not None and fld.max_length > 0) else "") + ("required=False," if (fld.null or fld.default == '') else "") + "),"
                if fld.name == 'gender':
                    content_text += '<tr><td>' + fld.name + '：</td><td>{% include "parts/gender.html" %}</td></tr>'
                elif fld.name == 'description':
                    content_text += '<tr><td>' + fld.name + '：</td><td><textarea name=' + fld.name + '>{{ mod.' + fld.name + ' }}</textarea></td></tr>'
                else:
                    content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'text').replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.BooleanField):
                args_text += "'" + fld.name + "': forms.BooleanField(required=False),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'checkbox').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateTimeField):
                args_text += "'" + fld.name + "': forms.DateTimeField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'datetime').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateField):
                args_text += "'" + fld.name + "': forms.DateField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'date').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.TextField):
                args_text += "'" + fld.name + "': forms.CharField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text2.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.IntegerField):
                args_text += "'" + fld.name + "': forms.IntegerField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.FloatField):
                args_text += "'" + fld.name + "': forms.FloatField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.ForeignKey):
                content_text += '<tr><td>' + fld.name + '：</td><td><a href="{% url "admin:activity:' + fld.rel.to._meta.db_table + '" mod.' + fld.name + '.id %}">{{ mod.' + fld.name + '.id }}</a></td></tr>'
        
        view_text += view_class_text.replace('{{cls_name}}', mod_name).replace('{{tbl_name}}', tbl_name).replace('{{args}}', args_text)
        template_file = codecs.open("./admin/templates/activity/" + tbl_name + ".html", "w", "utf-8")
        template_file.write(template_text.replace('{{content}}', content_text).replace('{{tbl_name}}', tbl_name))
        template_file.close()

        template2_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<table style="margin:30px">
    <tr>
        {% for item in list %}
            <td>活动名： </td>
            <td style="min-width: 200px;border:1px solid #C4D9AE;">{{ item.activity.name }}</td>
            <td><a href="{% url 'admin:activity:{{tbl_name}}' item.activity.id %}">查看</a></td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='activity_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='activity_admin' lb='activity' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='activity_admin' lb='activity' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
{% include 'parts/input_style.html' %}
{% endblock %}
"""
        template2_file = codecs.open("./admin/templates/activity/" + tbl_name + "_list.html", "w", "utf-8")
        template2_file.write(template2_text.replace('{{tbl_name}}', tbl_name))
        template2_file.close()

url_text += "]"
url_file = codecs.open("./admin/urls/activity.py", "w", "utf-8")
url_file.write(url_text)
url_file.close()

view_file = codecs.open("./admin/views/activity.py", "w", "utf-8")
view_file.write(view_text)
view_file.close()



# competition

import main.models.competition as competitions

url_text = """# Auto generated by generate.py
from django.conf.urls import url

from admin.views.competition import *

urls = ["""

view_text = """# Auto generated by generate.py
from django import forms
from django.http import HttpResponse
from django.template import loader, Context
from django.views.generic import View

from main.models.competition import *

from admin.utils.decorators import *
"""
view_class_text = """class {{cls_name}}View(View):
    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("competition/{{tbl_name}}.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        {{args}}
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("{{tbl_name}}", mod.id, 1, request.user)

        template = loader.get_template("competition/{{tbl_name}}.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class {{cls_name}}List(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = {{cls_name}}.objects.filter(competition_id=kwargs["id"])
            template = loader.get_template("competition/{{tbl_name}}_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:competition:{{tbl_name}}'})
            return HttpResponse(template.render(context))
        elif request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("competition/index.html")
            if {{cls_name}} == Competition:
                redir = 'admin:competition:competition'
            else:
                redir = 'admin:competition:{{tbl_name}}_list'
            context = Context({'name': name, 'list': Competition.objects.filter(name=name), 'redir': redir, 'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("competition/index.html")
            context = Context({'rb': '{{tbl_name}}'})
            return HttpResponse(template.render(context))
"""

for mod_name, mod_class in inspect.getmembers(competitions):
    if mod_name in competitions.__all__:
        template_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<form role="form" action="{% url 'admin:competition:{{tbl_name}}' mod.id %}" method="post">
<table>
    {{content}}
    <tr>
        <td>{{ msg }}</td>
        <td>
            <div class="buttons">
                <input type="submit" value="保存" />
                <input type="reset" value="取消" />
            </div>
        </td>
    </tr>
</table>
</form>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='activity_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='activity_admin' lb='competition' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='activity_admin' lb='competition' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
<style>
    form {
        padding: 30px;
    }
    form img {
        width: 100px;
        height: 100px;
    }
    td {
        padding: 5px 8px;
        vertical-align: top;
    }

    input[type=text], input[type=email], input[type=date], textarea {
        border: 2px solid #C5DBAD;
    }

    input[type=radio] {
        margin-right: 5px;
    }

    input[type=radio] ~ input {
        margin-left: 15px;
    }

    .buttons {
        float: right;
    }

    input[type=submit], input[type=reset] {
        border: 0 none;
        border-radius: 3px;
        padding: 2px 5px;
        background: #85A365;
        color: white;
        margin-left: 10px;
        margin-top: 10px;
    }

    input.tiny {
        width: 60px;
    }
</style>
{% endblock %}
"""
        template_contet_text = """<tr><td>{{text}}：</td><td><input name="{{name}}" type="{{type}}" value="{{ mod.{{name}} }}" {{minlen}}{{maxlen}}/></td></tr>"""
        template_contet_text2 = """<tr><td>{{text}}：</td><td><textarea name="{{name}}" {{minlen}}{{maxlen}}>{{ mod.{{name}} }}></textarea></td></tr>"""

        tbl_name = mod_class._meta.db_table
        
        url_text += "url(r'^" + tbl_name + "/list/(?P<id>\w+)?$', " + mod_name  + "List.as_view(), name='" + tbl_name + "_list'),url(r'^" + tbl_name + "/(?P<id>\w+)$', " + mod_name  + "View.as_view(), name='" + tbl_name + "'),"

        args_text = ""
        content_text = ""
        for fld in mod_class._meta.get_fields():
            if isinstance(fld, models.CharField):
                if fld.name == 'password':
                    continue
                args_text += "'" + fld.name + "': forms.CharField(" + ("max_length=" + str(fld.max_length) + "," if (fld.max_length is not None and fld.max_length > 0) else "") + ("required=False," if (fld.null or fld.default == '') else "") + "),"
                if fld.name == 'gender':
                    content_text += '<tr><td>' + fld.name + '：</td><td>{% include "parts/gender.html" %}</td></tr>'
                elif fld.name == 'description':
                    content_text += '<tr><td>' + fld.name + '：</td><td><textarea name=' + fld.name + '>{{ mod.' + fld.name + ' }}</textarea></td></tr>'
                else:
                    content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'text').replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.BooleanField):
                args_text += "'" + fld.name + "': forms.BooleanField(required=False),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'checkbox').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateTimeField):
                args_text += "'" + fld.name + "': forms.DateTimeField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'datetime').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateField):
                args_text += "'" + fld.name + "': forms.DateField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'date').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.TextField):
                args_text += "'" + fld.name + "': forms.CharField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text2.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.IntegerField):
                args_text += "'" + fld.name + "': forms.IntegerField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.FloatField):
                args_text += "'" + fld.name + "': forms.FloatField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.ForeignKey):
                content_text += '<tr><td>' + fld.name + '：</td><td><a href="{% url "admin:competition:' + fld.rel.to._meta.db_table + '" mod.' + fld.name + '.id %}">{{ mod.' + fld.name + '.id }}</a></td></tr>'
        
        view_text += view_class_text.replace('{{cls_name}}', mod_name).replace('{{tbl_name}}', tbl_name).replace('{{args}}', args_text)
        template_file = codecs.open("./admin/templates/competition/" + tbl_name + ".html", "w", "utf-8")
        template_file.write(template_text.replace('{{content}}', content_text).replace('{{tbl_name}}', tbl_name))
        template_file.close()

        template2_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<table style="margin:30px">
    <tr>
        {% for item in list %}
            <td>竞赛名： </td>
            <td style="min-width: 200px;border:1px solid #C4D9AE;">{{ item.competition.name }}</td>
            <td><a href="{% url 'admin:competition:{{tbl_name}}' item.competition.id %}">查看</a></td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='activity_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='activity_admin' lb='competition' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='activity_admin' lb='competition' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
{% include 'parts/input_style.html' %}
{% endblock %}
"""
        template2_file = codecs.open("./admin/templates/competition/" + tbl_name + "_list.html", "w", "utf-8")
        template2_file.write(template2_text.replace('{{tbl_name}}', tbl_name))
        template2_file.close()

url_text += "]"
url_file = codecs.open("./admin/urls/competition.py", "w", "utf-8")
url_file.write(url_text)
url_file.close()

view_file = codecs.open("./admin/views/competition.py", "w", "utf-8")
view_file.write(view_text)
view_file.close()



# forum

import main.models.forum as forums

url_text = """# Auto generated by generate.py
from django.conf.urls import url

from admin.views.forum import *

urls = ["""

view_text = """# Auto generated by generate.py
from django import forms
from django.http import HttpResponse
from django.template import loader, Context
from django.views.generic import View

from main.models.forum import *

from admin.utils.decorators import *
"""
view_class_text = """class {{cls_name}}View(View):
    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("forum/{{tbl_name}}.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record({{cls_name}}.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        {{args}}
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("{{tbl_name}}", mod.id, 1, request.user)

        template = loader.get_template("forum/{{tbl_name}}.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class {{cls_name}}List(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("forum/{{tbl_name}}_index.html")
            if {{cls_name}} == ForumPost:
                list = ForumPost.objects.filter(title=name)
            else:
                list = {{cls_name}}.objects.filter(name=name)
            context = Context({'name': name, 'list': list})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("forum/{{tbl_name}}_index.html")
            context = Context()
            return HttpResponse(template.render(context))
"""

for mod_name, mod_class in inspect.getmembers(forums):
    if mod_name in forums.__all__:
        template_text = """
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<form role="form" action="{% url 'admin:forum:{{tbl_name}}' mod.id %}" method="post">
<table>
    {{content}}
    <tr>
        <td>{{ msg }}</td>
        <td>
            <div class="buttons">
                <input type="submit" value="保存" />
                <input type="reset" value="取消" />
            </div>
        </td>
    </tr>
</table>
</form>
{% endblock %}

{% block topbar %}{% include 'topbar.html' with tb='forum_admin' %}{% endblock %}
{% block leftbar %}{% include 'leftbar.html' with tb='forum_admin' lb='forum' %}{% endblock %}
{% block rightbar %}{% include 'rightbar.html' with tb='forum_admin' lb='forum' rb='{{tbl_name}}' %}{% endblock %}

{% block css %}
<style>
    form {
        padding: 30px;
    }
    form img {
        width: 100px;
        height: 100px;
    }
    td {
        padding: 5px 8px;
        vertical-align: top;
    }

    input[type=text], input[type=email], input[type=date], textarea {
        border: 2px solid #C5DBAD;
    }

    input[type=radio] {
        margin-right: 5px;
    }

    input[type=radio] ~ input {
        margin-left: 15px;
    }

    .buttons {
        float: right;
    }

    input[type=submit], input[type=reset] {
        border: 0 none;
        border-radius: 3px;
        padding: 2px 5px;
        background: #85A365;
        color: white;
        margin-left: 10px;
        margin-top: 10px;
    }

    input.tiny {
        width: 60px;
    }
</style>
{% endblock %}
"""
        template_contet_text = """<tr><td>{{text}}：</td><td><input name="{{name}}" type="{{type}}" value="{{ mod.{{name}} }}" {{minlen}}{{maxlen}}/></td></tr>"""
        template_contet_text2 = """<tr><td>{{text}}：</td><td><textarea name="{{name}}" {{minlen}}{{maxlen}}>{{ mod.{{name}} }}></textarea></td></tr>"""

        tbl_name = mod_class._meta.db_table
        
        url_text += "url(r'^" + tbl_name + "/list$', " + mod_name  + "List.as_view(), name='" + tbl_name + "_list'),url(r'^" + tbl_name + "/(?P<id>\w+)$', " + mod_name  + "View.as_view(), name='" + tbl_name + "'),"

        args_text = ""
        content_text = ""
        for fld in mod_class._meta.get_fields():
            if isinstance(fld, models.CharField):
                if fld.name == 'password':
                    continue
                args_text += "'" + fld.name + "': forms.CharField(" + ("max_length=" + str(fld.max_length) + "," if (fld.max_length is not None and fld.max_length > 0) else "") + ("required=False," if (fld.null or fld.default == '') else "") + "),"
                if fld.name == 'gender':
                    content_text += '<tr><td>' + fld.name + '：</td><td>{% include "parts/gender.html" %}</td></tr>'
                elif fld.name == 'description':
                    content_text += '<tr><td>' + fld.name + '：</td><td><textarea name=' + fld.name + '>{{ mod.' + fld.name + ' }}</textarea></td></tr>'
                else:
                    content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'text').replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.BooleanField):
                args_text += "'" + fld.name + "': forms.BooleanField(required=False),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'checkbox').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateTimeField):
                args_text += "'" + fld.name + "': forms.DateTimeField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'datetime').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.DateField):
                args_text += "'" + fld.name + "': forms.DateField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'date').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.TextField):
                args_text += "'" + fld.name + "': forms.CharField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text2.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace("{{minlen}}", ' ').replace("{{maxlen}}", ('maxlength="'+str(fld.max_length)+'" ' if (fld.max_length is not None and fld.max_length > 0) else " "))
            elif isinstance(fld, models.IntegerField):
                args_text += "'" + fld.name + "': forms.IntegerField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.FloatField):
                args_text += "'" + fld.name + "': forms.FloatField(" + ("required=False," if (fld.null or fld.default is not None ) else "") + "),"
                content_text += template_contet_text.replace('{{text}}', fld.name).replace('{{name}}', fld.name).replace('{{type}}', 'number').replace("{{minlen}}{{maxlen}}", '')
            elif isinstance(fld, models.ForeignKey):
                content_text += '<tr><td>' + fld.name + '：</td><td><a href="{% url "admin:forum:' + fld.rel.to._meta.db_table + '" mod.' + fld.name + '.id %}">{{ mod.' + fld.name + '.id }}</a></td></tr>'
        
        view_text += view_class_text.replace('{{cls_name}}', mod_name).replace('{{tbl_name}}', tbl_name).replace('{{args}}', args_text)
        template_file = codecs.open("./admin/templates/forum/" + tbl_name + ".html", "w", "utf-8")
        template_file.write(template_text.replace('{{content}}', content_text).replace('{{tbl_name}}', tbl_name))
        template_file.close()

url_text += "]"
url_file = codecs.open("./admin/urls/forum.py", "w", "utf-8")
url_file.write(url_text)
url_file.close()

view_file = codecs.open("./admin/views/forum.py", "w", "utf-8")
view_file.write(view_text)
view_file.close()
