# Auto generated by generate.py
from django.conf.urls import url

from admin.views.competition import *

urls = [url(r'^competition/list/(?P<id>\w+)?$', CompetitionList.as_view(), name='competition_list'),url(r'^competition/(?P<id>\w+)$', CompetitionView.as_view(), name='competition'),url(r'^competition_comment/list/(?P<id>\w+)?$', CompetitionCommentList.as_view(), name='competition_comment_list'),url(r'^competition_comment/(?P<id>\w+)$', CompetitionCommentView.as_view(), name='competition_comment'),url(r'^competition_stage/list/(?P<id>\w+)?$', CompetitionStageList.as_view(), name='competition_stage_list'),url(r'^competition_stage/(?P<id>\w+)$', CompetitionStageView.as_view(), name='competition_stage'),url(r'^competition_team_participator/list/(?P<id>\w+)?$', CompetitionTeamParticipatorList.as_view(), name='competition_team_participator_list'),url(r'^competition_team_participator/(?P<id>\w+)$', CompetitionTeamParticipatorView.as_view(), name='competition_team_participator'),]