#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# Auto generated by activity.py
from django.conf.urls import url

from admin.views.activity.check import ActivityCheck
from admin.views.activity.list_detail import ActivityView, ActivityList

urls = [
    url(r'^(?P<activity_id>\d+)?/check/$', ActivityCheck.as_view(), name='activity_check'),

    # 老接口
    url(r'^activity/list/(?P<id>\w+)?$', ActivityList.as_view(), name='activity_list'),
    url(r'^activity/(?P<id>\w+)$', ActivityView.as_view(), name='activity'),
]
