#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# Auto generated by activity.py
from django.conf.urls import url

from admin.views.activity.check import ActivityCheck

urls = [
    url(r'^(?P<activity_id>\d+)?/check/$', ActivityCheck.as_view(), name='activity_check'),
]
