# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(db_index=True, default=0, verbose_name='访问次数')),
                ('last_visit_time', models.DateTimeField(db_index=True, verbose_name='最后一次访问时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_info', to='team.Team', verbose_name='团队')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_team_info', to='user.User')),
            ],
            options={
                'db_table': 'team_visitor',
            },
        ),
        migrations.CreateModel(
            name='UserVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(db_index=True, default=0, verbose_name='访问次数')),
                ('last_visit_time', models.DateTimeField(db_index=True, verbose_name='最后一次访问时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_info', to='user.User', verbose_name='用户')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_user_info', to='user.User')),
            ],
            options={
                'db_table': 'user_visitor',
            },
        ),
    ]
