# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('team', '0001_initial'),
        ('activity', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_info', to='activity.Activity', verbose_name='动态')),
            ],
            options={
                'db_table': 'activity_tag',
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_info', to='project.Project', verbose_name='项目')),
            ],
            options={
                'db_table': 'project_tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='名称')),
                ('activities', models.ManyToManyField(related_name='_tag_activities_+', through='tag.ActivityTag', to='activity.Activity')),
                ('projects', models.ManyToManyField(related_name='_tag_projects_+', through='tag.ProjectTag', to='project.Project')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='TeamTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tag.Tag', verbose_name='标签')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_info', to='team.Team', verbose_name='团队')),
            ],
            options={
                'db_table': 'team_tag',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tag.Tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_info', to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'user_tag',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='teams',
            field=models.ManyToManyField(related_name='_tag_teams_+', through='tag.TeamTag', to='team.Team'),
        ),
        migrations.AddField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(related_name='_tag_users_+', through='tag.UserTag', to='user.User'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tag.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='activitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tag.Tag', verbose_name='标签'),
        ),
    ]
