# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(db_index=True, verbose_name='建立关系时间')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_relationship', to='user.User')),
            ],
            options={
                'db_table': 'user_friend',
            },
        ),
        migrations.CreateModel(
            name='UserFriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_index=True, max_length=100, verbose_name='附带消息')),
                ('create_time', models.DateTimeField(db_index=True, verbose_name='申请时间')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='该申请是否已读')),
                ('is_ignored', models.BooleanField(db_index=True, default=False, verbose_name='该申请者是否已被忽略')),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requester_info', to='user.User', verbose_name='被申请者')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requested_info', to='user.User', verbose_name='申请者')),
            ],
            options={
                'db_table': 'user_friend_request',
                'ordering': ['-create_time'],
            },
        ),
    ]
