# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_index=True, max_length=200, verbose_name='内容')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发布时间')),
                ('modify_time', models.DateTimeField(blank=True, db_index=True, default=None, verbose_name='修改时间')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), size=None, verbose_name='图片附件')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', related_query_name='activity', to='user.User', verbose_name='作者')),
                ('team', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activities', related_query_name='activity', to='team.Team', verbose_name='所属团队')),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-create_time'],
            },
        ),
    ]
