# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='任务名称')),
                ('description', models.TextField(db_index=True, max_length=100, verbose_name='任务描述')),
                ('status', models.IntegerField(choices=[('未完成', 0), ('已完成', 1), ('已取消', 2)], db_index=True, default=0, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('expected_finish_time', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='预期完成时间')),
                ('actual_finish_time', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='实际完成时间')),
                ('executors', models.ManyToManyField(db_table='task_executors', related_name='tasks', related_query_name='task', to='user.User', verbose_name='任务执行者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to='team.Team')),
            ],
            options={
                'db_table': 'project_task',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskFinishMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_index=True, default='', max_length=100, verbose_name='备注')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='标记时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finish_marker', to='task.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.User', verbose_name='标记者')),
            ],
            options={
                'db_table': 'project_task_finish_marker',
            },
        ),
    ]
