# Auto generated by competition.py
from django.conf.urls import url

from admin.views.competition import *
from admin.views.competition.list_detail import CompetitionView, CompetitionList

urlpatterns = [
    url(r'^competition/list/(?P<id>\w+)?$', CompetitionList.as_view(), name='competition_list'),
    url(r'^competition/(?P<id>\w+)$', CompetitionView.as_view(), name='competition'),
    url(r'^competition_comment/list/(?P<id>\w+)?$', CompetitionCommentList.as_view(),
        name='competition_comment_list'),
    url(r'^competition_comment/(?P<id>\w+)$', CompetitionCommentView.as_view(), name='competition_comment'),
    url(r'^competition_file/list/(?P<id>\w+)?$', CompetitionFileList.as_view(), name='competition_file_list'),
    url(r'^competition_file/(?P<id>\w+)$', CompetitionFileView.as_view(), name='competition_file'),
    url(r'^competition_liker/list/(?P<id>\w+)?$', CompetitionLikerList.as_view(), name='competition_liker_list'),
    url(r'^competition_liker/(?P<id>\w+)$', CompetitionLikerView.as_view(), name='competition_liker'),
    url(r'^competition_notification/list/(?P<id>\w+)?$', CompetitionNotificationList.as_view(),
        name='competition_notification_list'),
    url(r'^competition_notification/(?P<id>\w+)$', CompetitionNotificationView.as_view(),
        name='competition_notification'),
    url(r'^competition_stage/list/(?P<id>\w+)?$', CompetitionStageList.as_view(), name='competition_stage_list'),
    url(r'^competition_stage/(?P<id>\w+)$', CompetitionStageView.as_view(), name='competition_stage'),
    url(r'^competition_team_participator/list/(?P<id>\w+)?$', CompetitionTeamParticipatorList.as_view(),
        name='competition_team_participator_list'),
    url(r'^competition_team_participator/(?P<id>\w+)$', CompetitionTeamParticipatorView.as_view(),
        name='competition_team_participator'),
]
