# Auto generated by generate.py
from django import forms
from django.http import HttpResponse
from django.template import loader, Context
from django.views.generic import View

from main.models.competition import *

from admin.utils.decorators import *
class CompetitionView(View):
    @fetch_record(Competition.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("competition/competition.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record(Competition.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        'name': forms.CharField(max_length=50,),'content': forms.CharField(max_length=1000,),'deadline': forms.DateTimeField(required=False,),'time_started': forms.DateTimeField(required=False,),'time_ended': forms.DateTimeField(required=False,),'time_created': forms.DateTimeField(required=False,),'allow_team': forms.BooleanField(required=False),'is_enabled': forms.BooleanField(required=False),
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("competition", mod.id, 1, request.user)

        template = loader.get_template("competition/competition.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class CompetitionList(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = Competition.objects.filter(competition_id=kwargs["id"])
            template = loader.get_template("competition/competition_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:competition:competition'})
            return HttpResponse(template.render(context))
        elif request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("competition/index.html")
            if Competition == Competition:
                redir = 'admin:competition:competition'
            else:
                redir = 'admin:competition:competition_list'
            context = Context({'name': name, 'list': Competition.objects.filter(name=name), 'redir': redir, 'rb': 'competition'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("competition/index.html")
            context = Context({'rb': 'competition'})
            return HttpResponse(template.render(context))
class CompetitionCommentView(View):
    @fetch_record(CompetitionComment.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("competition/competition_comment.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record(CompetitionComment.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        'content': forms.CharField(max_length=100,),'time_created': forms.DateTimeField(required=False,),
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("competition_comment", mod.id, 1, request.user)

        template = loader.get_template("competition/competition_comment.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class CompetitionCommentList(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = CompetitionComment.objects.filter(competition_id=kwargs["id"])
            template = loader.get_template("competition/competition_comment_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:competition:competition_comment'})
            return HttpResponse(template.render(context))
        elif request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("competition/index.html")
            if CompetitionComment == Competition:
                redir = 'admin:competition:competition'
            else:
                redir = 'admin:competition:competition_comment_list'
            context = Context({'name': name, 'list': Competition.objects.filter(name=name), 'redir': redir, 'rb': 'competition_comment'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("competition/index.html")
            context = Context({'rb': 'competition_comment'})
            return HttpResponse(template.render(context))
class CompetitionStageView(View):
    @fetch_record(CompetitionStage.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("competition/competition_stage.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record(CompetitionStage.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        'status': forms.IntegerField(required=False,),'province': forms.CharField(max_length=20,required=False,),'city': forms.CharField(max_length=20,required=False,),'min_member': forms.IntegerField(required=False,),'max_member': forms.IntegerField(required=False,),'school': forms.CharField(max_length=20,required=False,),'user_type': forms.IntegerField(required=False,),
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("competition_stage", mod.id, 1, request.user)

        template = loader.get_template("competition/competition_stage.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class CompetitionStageList(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = CompetitionStage.objects.filter(competition_id=kwargs["id"])
            template = loader.get_template("competition/competition_stage_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:competition:competition_stage'})
            return HttpResponse(template.render(context))
        elif request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("competition/index.html")
            if CompetitionStage == Competition:
                redir = 'admin:competition:competition'
            else:
                redir = 'admin:competition:competition_stage_list'
            context = Context({'name': name, 'list': Competition.objects.filter(name=name), 'redir': redir, 'rb': 'competition_stage'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("competition/index.html")
            context = Context({'rb': 'competition_stage'})
            return HttpResponse(template.render(context))
class CompetitionTeamParticipatorView(View):
    @fetch_record(CompetitionTeamParticipator.objects, 'mod', 'id')
    @require_cookie
    def get(self, request, mod):
        template = loader.get_template("competition/competition_team_participator.html")
        context = Context({'mod': mod})
        return HttpResponse(template.render(context))

    @fetch_record(CompetitionTeamParticipator.objects, 'mod', 'id')
    @require_cookie
    @validate_args2({
        
    })
    def post(self, request, mod, **kwargs):
        for k in kwargs:
            setattr(mod, k, kwargs[k])
        mod.save()

        admin_log("competition_team_participator", mod.id, 1, request.user)

        template = loader.get_template("competition/competition_team_participator.html")
        context = Context({'mod': mod, 'msg': '保存成功'})
        return HttpResponse(template.render(context))

class CompetitionTeamParticipatorList(View):
    @require_cookie
    @validate_args2({
        'page': forms.IntegerField(required=False, min_value=0),
    })
    def get(self, request, page=0, **kwargs):
        if kwargs["id"] is not None:
            list = CompetitionTeamParticipator.objects.filter(competition_id=kwargs["id"])
            template = loader.get_template("competition/competition_team_participator_list.html")
            context = Context({'page': page, 'list': list, 'redir': 'admin:competition:competition_team_participator'})
            return HttpResponse(template.render(context))
        elif request.GET.get("name") is not None:
            name = request.GET.get("name")
            template = loader.get_template("competition/index.html")
            if CompetitionTeamParticipator == Competition:
                redir = 'admin:competition:competition'
            else:
                redir = 'admin:competition:competition_team_participator_list'
            context = Context({'name': name, 'list': Competition.objects.filter(name=name), 'redir': redir, 'rb': 'competition_team_participator'})
            return HttpResponse(template.render(context))
        else:
            template = loader.get_template("competition/index.html")
            context = Context({'rb': 'competition_team_participator'})
            return HttpResponse(template.render(context))
