# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('username', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(db_index=True, max_length=128, verbose_name='密码')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='电子邮箱')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_active_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='最后一次活动时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='APP密钥')),
                ('expire_time', models.DateTimeField(verbose_name='到期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_info', to='user.User')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
    ]
