# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('activity', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker_info', to='activity.Activity')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_activity_info', to='user.User')),
            ],
            options={
                'db_table': 'activity_liker',
            },
        ),
        migrations.CreateModel(
            name='TeamLiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker_info', to='team.Team')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_team_info', to='user.User')),
            ],
            options={
                'db_table': 'team_liker',
            },
        ),
        migrations.CreateModel(
            name='UserLiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker_info', to='user.User')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user_info', to='user.User')),
            ],
            options={
                'db_table': 'user_liker',
            },
        ),
    ]
